### ISSUE TITLE
Dead code specification using uniqueness and well-scoped

### ISSUE THREAD

**Issue by basetunnel** [jaccokrijnen/plutus-cert#41]
## TODO

- [ ] Rewrite `Let` case with simple induction over both lists.
- [ ] Figure out how this spec seemingly solved the complexity with `letrec` compared to the other style of specification (there we would have to carry around the whole list of bindings to determine whether the bound var does not occur free in the post-term)
- [ ] Include strictness map
- [ ] Include datatype case where only type is used, but not constructors

## Former problem: how to prove this implies $x \notin FV(\texttt{let bs' in t'})$

__note: this is solved, see first comment__
I don't see a simple way of proving that $x \notin FV(\texttt{let bs' in t'})$, given $unique(\texttt{let bs' in t'})$ and $wellscoped(\texttt{let bs' in t'})$.

One way would be by considering the "context" (i.e. one-hole context of the term). The reasoning would go something like this:
- Suppose $x \in FV(...)$, where $x$ is a variable bound in an eliminated let
- Then there must be a binder in the context C' (of the post-term)
- Then there must be the same binder in the context C (of the pre-term)
- Then by uniqueness there is a contradiction in the pre-term, since it is bound twice.
